(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"QCD in the background field formalism",
  Authors -> {"V. Shtabovenko"},
  Version -> "1.0.0",
  Date -> "09. 10. 2014",
  Institutions -> {"Technische Universitaet Muenchen"},
  URLs -> "https://github.com/FeynCalc"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[5] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "g",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[5] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> ComposedChar["u", "g"],
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

V[50] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorType -> Cycles,
    InsertOnly -> {Internal, External},
    PropagatorArrow -> None,
    PropagatorLabel -> B,
    Mass -> 0 },

S[1] == {
    SelfConjugate -> True,
    Indices -> {Index[Colour], Index[Colour]},
    PropagatorLabel -> ComposedChar["h", Null, "0"],
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> 0 },

S[13] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> ComposedChar["U", Index[Generation]],
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MQU },

S[14] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> ComposedChar["D", Index[Generation]],
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MQD },

F[10] == {
    SelfConjugate -> False,
    Indices -> {Index[Colour], Index[Colour]},
    PropagatorLabel -> ComposedChar["H", Null, "0"],
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> ComposedChar["u", Index[Generation]],
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MQU },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> ComposedChar["d", Index[Generation]],
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MQD }
}


(*        Definitions       *)

FAGaugeXi[ V[5] ] = FAGaugeXi[G];
FAGaugeXi[ U[5] ] = FAGaugeXi[G];
FAGaugeXi[ V[50] ] = FAGaugeXi[G];

Mh0[ ___ ] := Mh0;
MQU[ 1, _ ] := 0;
MQU[ 1 ] := 0;
MQU[ 2, _ ] := 0;
MQU[ 2 ] := 0;
MQU[ 3, _ ] := 0;
MQU[ 3 ] := 0;
MQD[ 1, _ ] := 0;
MQD[ 1 ] := 0;
MQD[ 2, _ ] := 0;
MQD[ 2 ] := 0;
MQD[ 3, _ ] := 0;
MQD[ 3 ] := 0;
MQU[ 1, _ ] := 0;
MQU[ 1 ] := 0;
MQU[ 2, _ ] := 0;
MQU[ 2 ] := 0;
MQU[ 3, _ ] := 0;
MQU[ 3 ] := 0;
MQD[ 1, _ ] := 0
MQD[ 1 ] := 0
MQD[ 2, _ ] := 0
MQD[ 2 ] := 0
MQD[ 3, _ ] := 0
MQD[ 3 ] := 0


TheLabel[ V[5, {__}] ] := TheLabel[V[5]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ V[50, {__}] ] := TheLabel[V[50]];
TheLabel[ S[1, {__}] ] := TheLabel[S[1]];
TheLabel[ S[13, {1, _}] ] := "U";
TheLabel[ S[13, {1}] ] := "U";
TheLabel[ S[13, {2, _}] ] := "C";
TheLabel[ S[13, {2}] ] := "C";
TheLabel[ S[13, {3, _}] ] := "T";
TheLabel[ S[13, {3}] ] := "T";
TheLabel[ S[14, {1, _}] ] := "D";
TheLabel[ S[14, {1}] ] := "D";
TheLabel[ S[14, {2, _}] ] := "S";
TheLabel[ S[14, {2}] ] := "S";
TheLabel[ S[14, {3, _}] ] := "B";
TheLabel[ S[14, {3}] ] := "B";
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d"
TheLabel[ F[4, {1}] ] := "d"
TheLabel[ F[4, {2, _}] ] := "s"
TheLabel[ F[4, {2}] ] := "s"
TheLabel[ F[4, {3, _}] ] := "b"
TheLabel[ F[4, {3}] ] := "b"


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[50, {e1x2}] , V[50, {e2x2}] , V[50, {e3x2}] ] == {{-(FAGS*FASUNF[e1x2, e2x2, e3x2]), 0}, {FAGS*FASUNF[e1x2, e2x2, e3x2], 0}, {FAGS*FASUNF[e1x2, e2x2, e3x2], 0}, {-(FAGS*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(FAGS*FASUNF[e1x2, e2x2, e3x2]), 0}, {FAGS*FASUNF[e1x2, e2x2, e3x2], 0}, {0, 0}, {0, 0}, {0, 0}},

C[ V[50, {e1x2}] , V[50, {e2x2}] , V[5, {e3x2}] ] == {{-(FAGS*FASUNF[e1x2, e2x2, e3x2]), 0}, {FAGS*FASUNF[e1x2, e2x2, e3x2], 0}, {FAGS*FASUNF[e1x2, e2x2, e3x2], 0}, {-(FAGS*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(FAGS*FASUNF[e1x2, e2x2, e3x2]), 0}, {FAGS*FASUNF[e1x2, e2x2, e3x2], 0}, {(FAGS*FASUNF[e1x2, e2x2, e3x2])/FAGaugeXi[G], 0}, {-((FAGS*FASUNF[e1x2, e2x2, e3x2])/FAGaugeXi[G]), 0}, {0, 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[50, {e3x2}] ] == {{FAGS*FASUNF[e3x2, e1x1, e2x1], 0}, {-(FAGS*FASUNF[e3x2, e1x1, e2x1]), 0}},

C[ V[50, {e1x2}] , V[50, {e2x2}] , V[50, {e3x2}] , V[50, {e4x2}] ] == {{I*FAGS^2*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {(-I)*FAGS^2*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {(-I)*FAGS^2*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[50, {e3x2}] , V[50, {e4x2}] ] == {{I*FAGS^2*(FASUNF[e3x2, e1x1, e4x2, e2x1] + FASUNF[e3x2, e2x1, e4x2, e1x1]), 0}},

C[ V[50, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] ] == {{-(FAGS*FASUNF[e1x2, e2x2, e3x2]), 0}, {FAGS*FASUNF[e1x2, e2x2, e3x2], 0}, {FAGS*FASUNF[e1x2, e2x2, e3x2], 0}, {-(FAGS*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(FAGS*FASUNF[e1x2, e2x2, e3x2]), 0}, {FAGS*FASUNF[e1x2, e2x2, e3x2], 0}, {-((FAGS*FASUNF[e1x2, e2x2, e3x2])/FAGaugeXi[G]), 0}, {0, 0}, {(FAGS*FASUNF[e1x2, e2x2, e3x2])/FAGaugeXi[G], 0}},

C[ V[50, {e1x2}] , V[50, {e2x2}] , V[50, {e3x2}] , V[5, {e4x2}] ] == {{I*FAGS^2*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {(-I)*FAGS^2*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {(-I)*FAGS^2*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[5, {e3x2}] ] == {{FAGS*FASUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[50, {e3x2}] , V[5, {e4x2}] ] == {{I*FAGS^2*FASUNF[e3x2, e1x1, e4x2, e2x1], 0}},

C[ V[50, {e1x2}] , V[50, {e2x2}] , V[5, {e3x2}] , V[5, {e4x2}] ] == {{(I*FAGS^2*(FAGaugeXi[G]*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]) - FASUNF[e1x2, e4x2, e2x2, e3x2]))/FAGaugeXi[G], 0}, {((-I)*FAGS^2*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FAGaugeXi[G]*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2])))/FAGaugeXi[G], 0}, {(-I)*FAGS^2*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ V[5, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] ] == {{-(FAGS*FASUNF[e1x2, e2x2, e3x2]), 0}, {FAGS*FASUNF[e1x2, e2x2, e3x2], 0}, {FAGS*FASUNF[e1x2, e2x2, e3x2], 0}, {-(FAGS*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(FAGS*FASUNF[e1x2, e2x2, e3x2]), 0}, {FAGS*FASUNF[e1x2, e2x2, e3x2], 0}, {0, 0}, {0, 0}, {0, 0}},

C[ V[50, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] , V[5, {e4x2}] ] == {{I*FAGS^2*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {(-I)*FAGS^2*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {(-I)*FAGS^2*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ V[5, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] , V[5, {e4x2}] ] == {{I*FAGS^2*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {(-I)*FAGS^2*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {(-I)*FAGS^2*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1, {e3x1, e3x2}] ] == {{I*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e3x1]*IndexDelta[e2x3, e3x2], 0}, {I*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e3x1]*IndexDelta[e2x3, e3x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1, {e3x1, e3x2}] ] == {{I*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e3x1]*IndexDelta[e2x3, e3x2], 0}, {I*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e3x1]*IndexDelta[e2x3, e3x2], 0}},

C[ S[14, {e1x1, e1x2}] , -S[14, {e2x1, e2x2}] , S[1, {e3x1, e3x2}] ] == {{I*IndexDelta[e1x1, e2x1]*IndexDelta[e2x2,e3x2]*IndexDelta[e1x2,e3x1], 0}},

C[ S[14, {e1x1, e1x2}] , S[14, {e2x1, e2x2}] , S[1, {e3x1, e3x2}] ] == {{I*IndexDelta[e1x1, e2x1]*IndexDelta[e2x2,e3x2]*IndexDelta[e1x2,e3x1], 0}},

C[ -S[14, {e1x1, e1x2}] , -S[14, {e2x1, e2x2}] , S[1, {e3x1, e3x2}] ] == {{I*IndexDelta[e1x1, e2x1]*IndexDelta[e1x2,e3x2]*IndexDelta[e2x2,e3x1], 0}},

C[ S[14, {e2x1, e2x2}] , -S[14, {e3x1, e3x2}] , V[50, {e1x2}] ] == {{(-I)*FAGS*IndexDelta[e2x1, e3x1]*FASUNT[e1x2, e3x2, e2x2], 0}, {I*FAGS*IndexDelta[e2x1, e3x1]*FASUNT[e1x2, e3x2, e2x2], 0}},

C[ S[14, {e1x1, e1x2}] , -S[14, {e2x1, e2x2}] , V[5, {e3x2}] ] == {{(-I)*FAGS*IndexDelta[e1x1, e2x1]*FASUNT[e3x2, e2x2, e1x2], 0}, {I*FAGS*IndexDelta[e1x1, e2x1]*FASUNT[e3x2, e2x2, e1x2], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[50, {e3x2}] ] == {{(-I)*FAGS*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], 0}, {(-I)*FAGS*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[50, {e3x2}] ] == {{(-I)*FAGS*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], 0}, {(-I)*FAGS*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[5, {e3x2}] ] == {{(-I)*FAGS*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], 0}, {(-I)*FAGS*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[5, {e3x2}] ] == {{(-I)*FAGS*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], 0}, {(-I)*FAGS*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], 0}},

C[ S[14, {e3x1, e3x2}] , -S[14, {e4x1, e4x2}] , V[50, {e1x2}] , V[50, {e2x2}] ] == {{I*FAGS^2*IndexDelta[e3x1, e4x1]*(FASUNT[e1x2, e2x2, e4x2, e3x2] + FASUNT[e2x2, e1x2, e4x2, e3x2]), 0}},

C[ S[14, {e2x1, e2x2}] , -S[14, {e3x1, e3x2}] , V[50, {e1x2}] , V[5, {e4x2}] ] == {{I*FAGS^2*IndexDelta[e2x1, e3x1]*(FASUNT[e1x2, e4x2, e3x2, e2x2] + FASUNT[e4x2, e1x2, e3x2, e2x2]), 0}},

C[ S[14, {e1x1, e1x2}] , -S[14, {e2x1, e2x2}] , V[5, {e3x2}] , V[5, {e4x2}] ] == {{I*FAGS^2*IndexDelta[e1x1, e2x1]*(FASUNT[e3x2, e4x2, e2x2, e1x2] + FASUNT[e4x2, e3x2, e2x2, e1x2]), 0}},

C[ -F[3, {e1x2, e1x3}] , F[10, {e2x2, e2x3}] , S[13, {e3x1, e3x2}] ] == {{I*IndexDelta[e1x2, e3x1]*IndexDelta[e3x2,e2x2]*IndexDelta[e2x3,e1x3], 0}, {I*IndexDelta[e1x2, e3x1]*IndexDelta[e3x2,e2x2]*IndexDelta[e2x3,e1x3], 0}},

C[ S[13, {e2x1, e2x2}] , -S[13, {e3x1, e3x2}] , V[50, {e1x2}] ] == {{(-I)*FAGS*IndexDelta[e2x1, e3x1]*FASUNT[e1x2, e3x2, e2x2], 0}, {I*FAGS*IndexDelta[e2x1, e3x1]*FASUNT[e1x2, e3x2, e2x2], 0}},

C[ S[13, {e2x1, e2x2}] , -S[13, {e3x1, e3x2}] , V[5, {e1x2}] ] == {{(-I)*FAGS*IndexDelta[e2x1, e3x1]*FASUNT[e1x2, e3x2, e2x2], 0}, {I*FAGS*IndexDelta[e2x1, e3x1]*FASUNT[e1x2, e3x2, e2x2], 0}},

C[ -F[10, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -S[13, {e3x1, e3x2}] ] == {{I*IndexDelta[e2x2, e3x1]*IndexDelta[e3x2,e1x2]*IndexDelta[e2x3,e1x3], 0}, {I*IndexDelta[e2x2, e3x1]*IndexDelta[e3x2,e1x2]*IndexDelta[e2x3,e1x3], 0}},

C[ S[1, {e1x1, e1x2}] , S[13, {e2x1, e2x2}] , -S[13, {e3x1, e3x2}] ] == {{I*IndexDelta[e2x1, e3x1]*IndexDelta[e3x2,e1x2]*IndexDelta[e2x2,e1x1], 0}},

C[ S[1, {e1x1, e1x2}] , S[13, {e2x1, e2x2}] , S[13, {e3x1, e3x2}] ] == {{I*IndexDelta[e2x1, e3x1]*IndexDelta[e3x2,e1x2]*IndexDelta[e2x2,e1x1], 0}},

C[ S[1, {e1x1, e1x2}] , -S[13, {e2x1, e2x2}] , -S[13, {e3x1, e3x2}] ] == {{I*IndexDelta[e2x1, e3x1]*IndexDelta[e2x2,e1x2]*IndexDelta[e3x2,e1x1], 0}},

C[ S[13, {e3x1, e3x2}] , -S[13, {e4x1, e4x2}] , V[50, {e1x2}] , V[50, {e2x2}] ] == {{I*FAGS^2*IndexDelta[e3x1, e4x1]*(FASUNT[e1x2, e2x2, e4x2, e3x2] + FASUNT[e2x2, e1x2, e4x2, e3x2]), 0}},

C[ S[13, {e3x1, e3x2}] , -S[13, {e4x1, e4x2}] , V[50, {e1x2}] , V[5, {e2x2}] ] == {{I*FAGS^2*IndexDelta[e3x1, e4x1]*(FASUNT[e1x2, e2x2, e4x2, e3x2] + FASUNT[e2x2, e1x2, e4x2, e3x2]), 0}},

C[ S[13, {e3x1, e3x2}] , -S[13, {e4x1, e4x2}] , V[5, {e1x2}] , V[5, {e2x2}] ] == {{I*FAGS^2*IndexDelta[e3x1, e4x1]*(FASUNT[e1x2, e2x2, e4x2, e3x2] + FASUNT[e2x2, e1x2, e4x2, e3x2]), 0}}

}

